/**
 * 접수 검증 설정 — 값 변경 시 이 파일만 수정
 */
var SUBMIT_VALIDATION_CONFIG = {
  TOKEN_TTL_SECONDS: 600,
  FAST_SUBMIT_SECONDS: 7,
  VERY_FAST_SUBMIT_SECONDS: 2,
  DUPLICATE_PHONE_TTL_SECONDS: 86400,
  ENABLE_FAST_SUBMIT_CONVERSION: true,
  REQUIRE_AD_SIGNAL_FOR_CONVERSION: true
};
